In [1]:
import math
import numpy as np
import h5py
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.python.framework import ops
from tf_utils import load_dataset, random_mini_batches, convert_to_one_hot, predict
from IPython.display import display, Math, Latex, HTML
%matplotlib inline
np.random.seed(1)

In [4]:
CSS = """
.output {
    flex-direction: row;
}
"""

HTML('<style>{}</style>'.format(CSS))

# Constructing Basic Graph 
![title](tfimages/basicgraph.PNG)

# Initializing the Variables

In [5]:
a = tf.constant(8)
b = tf.constant(2)
c = tf.constant(3)


In [6]:
d = tf.multiply(a,b); e = tf.add(c,b); f = tf.subtract(d,e)

 # Illustration of our first constructed graph
 ![title](images/tf_node.png)

In [7]:
sess = tf.Session(); outs = sess.run(d); sess.close(); print("outs = {}".format(outs))

outs = 16


# Creating and Running the Session

In [8]:
sess = tf.Session()
print(sess.run(d))

16


# Graphical Display of Flowing Tensors
![title](tfimages/skeleton.PNG)

# Placeholders

In [9]:
x = tf.placeholder(tf.int64, name = 'x')
print(sess.run(2 * x, feed_dict = {x: 3}))
sess.close()

6


# Defining a Linear Function (y=wx+b)

In [10]:
def linear_function():
        np.random.seed(1)
        X = tf.constant(np.random.randn(3,1),name = "X")
        W = tf.constant(np.random.randn(4,3),name = "W")
        b = tf.constant(np.random.randn(4,1),name = "b")
        Y = tf.add(tf.matmul(W,X),b)
        sess = tf.Session()
        result = sess.run(Y)
        return result

In [15]:
np.random.seed(4)
a= np.random.randn(3,1);print(a)

[[ 0.05056171]
 [ 0.49995133]
 [-0.99590893]]


In [9]:
print( "result = " + str(linear_function()))

result = [[-2.15657382]
 [ 2.95891446]
 [-1.08926781]
 [-0.84538042]]


# Metohds to Invoke TF Sessions
## Method 1
sess = tf.Session()
#Run the variables initialization (if needed), run the operations

result = sess.run(..., feed_dict = {...})

sess.close() # Close the session

## Method 2
with tf.Session() as sess: 
    # run the variables initialization (if needed), run the operations
    result = sess.run(..., feed_dict = {...})
    # This takes care of closing the session for you


# Computing the Sigmoid

In [20]:
def sigmoid(z):
    x = tf.placeholder(tf.float64, name="x")
    sigmoid = tf.math.sigmoid(x,name='sig')
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        result = sess.run(sigmoid,feed_dict={x:z})
        return result

In [21]:
print(sigmoid(11))

0.999983298578152


# Computing loss = (y_hat - y)^2


In [22]:
display(Math(r'\square{y_hat - y}')) 

<IPython.core.display.Math object>

In [23]:
y_hat = tf.constant(36, name='y_hat') 
y = tf.constant(39, name='y') 
loss = tf.Variable((y - y_hat)**2, name='loss') 
init = tf.global_variables_initializer() 
with tf.Session() as session:
    session.run(init) 
    print(session.run(loss)) 

9


# Cost Function −(ylog(p)+(1−y)log(1−p)

In [24]:
def cost(logits, labels):
    z=tf.placeholder(tf.float64,name="z")
    y=tf.placeholder(tf.float64,name="y")
    cost = tf.nn.sigmoid_cross_entropy_with_logits(logits=z,labels=y)
    sess = tf.Session()
    cost = sess.run(cost, feed_dict={z:logits,y:labels})
    sess.close()
    return cost

In [25]:
logits = sigmoid(np.array([0.2,0.4,0.7,0.9]))
cost = cost(logits, np.array([0,0,1,1]))
print ("cost = " + str(cost))

cost = [1.00538722 1.03664083 0.41385432 0.39956614]


#### Notice that in Above Dimension of Cost is same as dimnesion of logits for predicts and actual labels, hence its element wise.
#### In most of real examples, ,this is reduced to a single value using tf.reduce_mean(cost) and becomes the observed value 
#### to be reduced to minimum.

# One Hot encodings in Tensorflow

In [26]:
def one_hot_matrix(labels, C):
    C = tf.constant(name="C",value=C)
    one_hot_matrix = tf.one_hot(labels,C,axis=1)
    sess = tf.Session()
    one_hot = sess.run(one_hot_matrix)
    sess.close()
    return one_hot

In [27]:

labels = np.array([1,2,3,0,2,1])
one_hot = one_hot_matrix(labels, C = 4)
print ("one_hot = " + str(one_hot))

one_hot = [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]


In [28]:
labels = np.random.randint(0,10,6)
one_hot = one_hot_matrix(labels, C = 10)
display(one_hot)
display(labels)

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

array([5, 8, 9, 5, 0, 0])

In [29]:
#### important point to note that one-Hot encoding is useful for many categorical and ordinal variables to be represented them
#### in numerical format. 

#  Initialize with zeros and ones

In [30]:
def ones(shape):
    ones = tf.ones(shape)
    sess = tf.Session()
    ones = sess.run(ones)
    sess.close()
    return ones

In [31]:
print ("ones = " + str(ones([3])))

ones = [1. 1. 1.]
